import { ChakraProvider } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Press_Start_2P } from 'next/font/google'

const pressStart = Press_Start_2P({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Jogo Trilha",
  description: "Generated by create next app",
  icons: {
    icon: './icon.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        style={{
          margin: 0,
          padding: 0,
          width: "100vw",
          height: "100vh"
        }}
        className={pressStart.className}
      >
        <App>
          {children}
        </App>
      </body>
    </html>
  );
}

function App({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ChakraProvider>
      {children}
    </ChakraProvider>
  )
}
